In [2]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [4]:
boston = load_boston()
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [10]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [5]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

In [6]:
y_data.shape

(506, 1)

In [7]:
from sklearn import preprocessing


# 스케일링
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [38]:
from sklearn.model_selection import train_test_split

# train test 데이터 생성
X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size=0.33)

In [39]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [29]:
from sklearn import linear_model
regr = linear_model.LinearRegression(fit_intercept=True,    # 상수항을 넣을건지 말건지
                                     normalize=False,       # 이미 스케일링 했으므로 False
                                     copy_X=True,           # 복사해서 작업
                                     n_jobs=8)              # cpu를 몇개 쓸껀가
regr.fit(X_train, y_train)   #모델이 생성된다.
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [30]:
regr.coef_ , regr.intercept_

(array([[-1.83461064,  1.09381048,  0.02616482,  0.35794312, -2.1384334 ,
          3.2163187 ,  0.21587634, -3.68063499,  1.32540932, -1.14074851,
         -1.68714481,  0.55496177, -4.17614968]]), array([30.33244195]))

In [31]:
# # The coefficients
print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)

Coefficients:  [[-1.83461064  1.09381048  0.02616482  0.35794312 -2.1384334   3.2163187
   0.21587634 -3.68063499  1.32540932 -1.14074851 -1.68714481  0.55496177
  -4.17614968]]
intercept:  [30.33244195]


In [41]:
y_pred=regr.predict(X_test)
y_pred

array([[21.33087892],
       [18.14505618],
       [21.27737327],
       [20.40572718],
       [23.6117079 ],
       [12.63775288],
       [20.43221515],
       [14.98022872],
       [16.7041763 ],
       [15.15987247],
       [28.94016063],
       [18.4619646 ],
       [30.93824718],
       [28.40178314],
       [20.73280762],
       [23.1382519 ],
       [31.93566428],
       [27.09378331],
       [35.60596129],
       [33.98022921],
       [23.2250539 ],
       [26.91464641],
       [25.10432851],
       [31.24866829],
       [16.33138756],
       [20.23242879],
       [17.01274873],
       [22.56286596],
       [36.82675153],
       [ 6.91867639],
       [30.58329235],
       [30.73858435],
       [34.32192783],
       [34.02298639],
       [21.52726472],
       [16.67073894],
       [20.20194968],
       [18.80483818],
       [26.82320066],
       [33.24767001],
       [22.53196797],
       [25.61820324],
       [34.65938092],
       [ 8.21617492],
       [19.01469969],
       [25

In [47]:
# 안나누고 그냥 x_scaled_data의 값을 바로 예측 5번까지
## 이건 별로 신경안써도될듯
regr.predict(x_scaled_data[:10])

array([[30.27797413],
       [25.27765047],
       [30.34974045],
       [28.32762959],
       [27.5151593 ],
       [25.40958232],
       [22.90065214],
       [19.20030483],
       [11.06646423],
       [18.60278466]])

In [ ]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_    

# 평가

In [45]:
# RMSE1
np.sqrt(((y_test-y_pred)**2).sum()/len(y_test))

4.360541760601323

In [49]:
# RMSE2
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,y_pred))

4.360541760601323

In [16]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:
y_true = y_test
y_hat = regr.predict(X_test)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

In [ ]:
y_true = y_train
y_hat = regr.predict(X_train)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)